####################################################################################################################
### model that gets structured input from Spectos platform and outputs an e-mail answer based on training data
####################################################################################################################

from transformers import AutoModelForSeq2SeqLM, AutoModelForCausalLM, AutoTokenizer
from typing import Union
import torch

class seq2seq_email_model:
    device: torch.device
    model: Union[AutoModelForCausalLM, AutoModelForSeq2SeqLM]
    tokenizer: AutoTokenizer

    def __init__(self, config, device=None):
        if not device:
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = device
        #load model and tokenizer
        self.model = AutoModelForSeq2SeqLM.from_pretrained(config.model_name)
        #put model in eval mode
        self.model.to(self.device)
        self.model.eval()
        self.tokenizer = AutoTokenizer.from_pretrained(config.model_name)
        #set truncation to left
        self.tokenizer.truncation_side = "left"

    def generate_email_from_data(self, inputsequence: str, anredencheck=False, sample=False) -> str:
        #input: structured data input with prompt prepended via data_preparation.get_input_string_from_dict
        #output: output e-mail generated by the model
        #anredencheck: if True check for greeting in output and put it in if it is not present
        #sample: if True sample using temperature sampling to generate different outputs in every generation

        #tokenize the input
        tokenized_input = self.tokenizer(inputsequence, return_tensors="pt", max_length=850, truncation=True)
        tokenized_output = self.model.generate(tokenized_input["input_ids"].to(self.device), 
                                                attention_mask=tokenized_input["attention_mask"].to(self.device), 
                                                max_new_tokens=self.tokenizer.model_max_length,
                                                do_sample=sample,
                                                )
        output = self.tokenizer.decode(tokenized_output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)


        #prüfe anrede
        anreden_liste = ["sehr geehrte", "sehr geehrter", "guten tag", "hallo"]
        verabschiedungs_liste = ["freundliche grüße", "freundlichen grüßen", "beste grüße", "besten grüßen"]
        if anredencheck:
            keine_anrede = False
            keine_verabschiedung = False
            lower_output = output.lower()
            if not any(anrede in lower_output for anrede in anreden_liste):
                
                keine_anrede = True
            if not any(verabschiedung in lower_output for verabschiedung in verabschiedungs_liste):
                
                keine_verabschiedung = True

            if keine_anrede:
                #add Guten Tag at beginning
                output = "Guten Tag, \n" + output
            if keine_verabschiedung:
                #add Mit freundlichen Grüßen at the end
                output = output + "\nMit freundlichen Grüßen"
        

        return output

