####################################################################################################################
#generation API
#create a client with the port and IP
#generate an answer either based on an ID or the entire input for the model
####################################################################################################################

import socket

class generation_client:
    hostname: str
    port: int

    def __init__(self, hostname=socket.gethostname(), port=12345):
        self.hostname = hostname
        self.port = port

    def generate_answer_from_input(self, input_text: str) -> str:
        #input: text with instruction Generiere eine Reklamationsantwort E-Mail aus den folgenden Daten and the columns specified in the readme
        #output: answer generated by model on server

        client_socket = socket.socket()  # instantiate client
        client_socket.connect((self.hostname, self.port))  # connect to the server

        client_socket.send(input_text.encode())  # send input text
        response = client_socket.recv(8192).decode()  # receive response

        client_socket.close() #close the socket

        return response


    def generate_answer_from_id(self, input_id: str) -> str:
        #input: reklamations ID
        #output: answer generated by model on server based on the information for the reklamations ID

        client_socket = socket.socket()  # instantiate client
        client_socket.connect((self.hostname, self.port))  # connect to the server

        client_socket.send(input_id.encode())  # send input text
        response = client_socket.recv(8192).decode()  # receive response

        client_socket.close() #close the socket

        return response
