####################################################################################################################
### model that gets structured input from Spectos platform and outputs an e-mail answer based on training data
####################################################################################################################

from transformers import AutoModelForSeq2SeqLM, AutoModelForCausalLM, AutoTokenizer
from typing import Union
import torch

class seq2seq_email_model:
    device: torch.device
    model: Union[AutoModelForCausalLM, AutoModelForSeq2SeqLM]
    tokenizer: AutoTokenizer

    def __init__(self, config, device=None):
        if not device:
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = device
        #load model and tokenizer
        self.model = AutoModelForSeq2SeqLM.from_pretrained(config.model_name)
        #put model in eval mode
        self.model.to(self.device)
        self.model.eval()
        self.tokenizer = AutoTokenizer.from_pretrained(config.model_name)
        #set truncation to left
        self.tokenizer.truncation_side = "left"

    def generate_email_from_data(self, inputsequence: str) -> str:
        #input: structured data input with prompt prepended via data_preparation.get_input_string_from_dict
        #output: output e-mail generated by the model

        #tokenize the input
        tokenized_input = self.tokenizer(inputsequence, return_tensors="pt", max_length=850, truncation=True)
        tokenized_output = self.model.generate(tokenized_input["input_ids"].to(self.device), 
                                                attention_mask=tokenized_input["attention_mask"].to(self.device), 
                                                max_new_tokens=self.tokenizer.model_max_length,
                                                #sampling/non-deterministic

                                                #multinomial_sampling
                                                #do_sample=True,
                                                #num_beams=1,
                                                #temperature=0.1,

                                                

                                                #beam search multinomial
                                                #num_beams=5,
                                                #do_sample=True,
                                                #temperature=0.7,


                                                #nucleus sampling
                                                #do_sample=True,
                                                #top_p=0.85,
                                                #top_k=0,

                                                #top_k sampling
                                                #do_sample=True,
                                                #top_k=10,


                                                #deterministic 

                                                #beam search
                                                #num_beams=5,

                                                #contrastive search
                                                # penalty_alpha=0.6,
                                                # top_k=10,
                                                )
        output = self.tokenizer.decode(tokenized_output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)

        

        return output

